### PR TITLE
Fix sorting in frontend

### PR DESCRIPTION
**Pull request by Sympatron**

### CODE REVIEW

**Comment by tdittr** [comment]
Hey, thanks for the contribution! 

Could you describe what/how this change fixes the sorting? Are strings now sorted differently?

**Comment by Sympatron** [comment]
Strings should be sorted the same. The problem was that the sort function should only return `0` if both values are equal. Otherwise it should return a positive or negative number depending on the order.
The second problem was that `Array.sort` does not return a new array, but sorts in-place instead. `Array.toSorted` is the correct function here.

Everything is sorted descending except for crate names. I think this makes the most sense.

**Comment by Sympatron** [comment]
Done.

**Comment by tdittr** [comment]
Thank you :)

Looks like the crates.io dump format changed, so CI failed. I merged #99 which should fix this. Can you rebase/merge from main once more? Sorry for the extra steps :(

**Pull request merged**
